# Generated by Django 5.0.3 on 2024-05-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_inventory_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='replenishmentrequest',
            name='reason',
            field=models.TextField(null=True),
        ),
    ]
