# Generated by Django 5.0.3 on 2024-06-01 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_replenishmentrequest_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockcount',
            name='location',
        ),
        migrations.RemoveField(
            model_name='stockcount',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('put_away', 'Put Away'), ('pick', 'Pick'), ('pack', 'Pack'), ('delivery', 'Delivery'), ('receive', 'Receive'), ('transfer', 'Transfer'), ('adjustment', 'Adjustment'), ('cycle_count', 'Cycle Count'), ('replenishment', 'Replenishment'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('out_of_stock', 'Out Of Stock'), ('expired', 'Expired')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('received', 'Received'), ('put_away', 'Put Away')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='DeliveryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_company', models.CharField(max_length=100)),
                ('delivery_man_name', models.CharField(max_length=100)),
                ('delivery_man_phone', models.CharField(max_length=15)),
                ('date_assigned', models.DateField(auto_now_add=True)),
                ('orders', models.ManyToManyField(to='backend.order')),
            ],
        ),
        migrations.DeleteModel(
            name='PickingList',
        ),
        migrations.DeleteModel(
            name='StockCount',
        ),
    ]
