# Generated by Django 5.0.3 on 2024-06-15 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_remove_stockcount_location_remove_stockcount_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='to_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_location', to='backend.location'),
        ),
    ]
