# Generated by Django 5.0.3 on 2024-06-20 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_stockmovement_to_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='data',
            field=models.TextField(),
        ),
    ]
